### ISSUE TITLE
Inheriting from `Typed` controller with element's type

### ISSUE THREAD

**Issue by mlwyatt** [ajaishankar/stimulus-typescript#3]
Hello. 

I've been using a custom tweaked version of this package for some time and I'm struggling to come up with a solution to my problem. I'm trying provide the controller's `element` type **and** extend a common (abstract) controller.

Any insights would be appreciated.

```ts
const targets = { confirmModal: HTMLElement };

// This line causes "Base class expressions cannot reference class type parameters."
abstract class HasConfimationController<ElementType extends Element = Element> extends Typed(Controller<ElementType>, { targets }) {
  abstract confirmField({ detail: { data } }: CustomEvent): void;
  abstract declineField({ detail: { data } }: CustomEvent): void;

  protected callConfirmation(): void {
    // Open confirmation dialog
  }
}

class DeleteController extends HasConfimationController<HTMLElement> {
  confirmField(): void {
    // Handle confirm
  }
  
  declineField(): void {
    // Handle confirm
  }
}
```

**Comment by ajaishankar** [comment]
The following should work... 

It moves the type argument outside the class declaration.

```ts
function HasConfimationController<T extends Element = Element>() {
  const targets = { confirmModal: HTMLElement };

  abstract class HasConfimationController extends Typed(Controller<T>, {
    targets,
  }) {
    abstract confirmField({ detail: { data } }: CustomEvent): void;
    abstract declineField({ detail: { data } }: CustomEvent): void;

    protected callConfirmation(): void {
      // Open confirmation dialog
    }
  }

  return HasConfimationController;
}

class DeleteController extends HasConfimationController<HTMLElement>() {
  confirmField(): void {
    // Handle confirm
  }

  declineField(): void {
    // Handle confirm
  }
}
```

Curious why you are using a tweaked version of the library?

**Comment by mlwyatt** [comment]
> ```ts
> function HasConfimationController<T extends Element = Element>() {
> ...
> }
> 
> class DeleteController extends HasConfimationController<HTMLElement>() {
> ```
>

Ah, thanks. I didn't think of that

> Curious why you are using a tweaked version of the library?

It's been a while since I really looked at it but I think it was just adding/fixing something from an old version that's since been added/fixed
